export const accessToken =
  "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0ZjNlNDgyYmFjNTNiYmRmNjhmYjEzMDNmZmNlMTA3YiIsInN1YiI6IjY0NjZlYmU2MzNhMzc2MDEzYjNkMjk3YiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.AvuTTZQRaQ6ZVrXTKPJAZ3Mc3iyu0RLbPTvW-bX2QD0";
  export const imageUrl='https://image.tmdb.org/t/p/original'